### ISSUE TITLE
No method to get key from a node?

### ISSUE THREAD

**Issue by tv42** [kellydunn/go-art#4]
This makes e.g. iterating the tree a bit pointless; you can't even round-trip a map[string]string to ART and back (without kludges).

**Comment by kellydunn** [comment]
Do you mean exposing something like:

``` golang
func(n *ArtNode) Key() []byte {
  return n.key
}
```

I think that's perfectly reasonable.

**Comment by tv42** [comment]
Yes. Beware your 0-termination there.

**Comment by kellydunn** [comment]
Actually, this brings up an interesting point;  the `key` to a `ArtNode` is an implementation detail due to how the specification describes how the Node is stored in the Tree (The 0-termination is to prevent prefix collisions). Thusly, retrieving the `key` from a `ArtNode` wouldn't necessarily always yield what the user inserted for any particular leaf.  

As you allude, the 0-termination could return a key with an additional (undesirable) empty byte. 

Could you perhaps elaborate a bit more on your use case so I could understand what you're trying to accomplish with this new feature?  It might help me understand a bit more about what would be the desired return value of exposing the key.  Are you expecting the original path to be returned for a given node?  How do you envision this behavior working for non-leaf nodes?

**Comment by tv42** [comment]
I have no interest in non-leaf nodes; those I consider an internal implementation detail.

What got me here is a general interest in data structures, including ART trees, and https://github.com/tv42/benchmark-ordered-map

Part of that benchmark is an iterate workload that just gets the key and value of every item.

I guess what this means is I'll do `tree.insert(key, item)` instead of `tree.insert(key, value)`, where item is a `struct { Key, Value }`. That's fine, and I have other data structures in the benchmark that already need that; not everything stores the unprocessed key, and it sounds like that's the case here.

**Comment by kellydunn** [comment]
Ah I see!

I'm honored that you're considering to evaluate `go-art`! I'd be very interested to learn about your findings :)

> I guess what this means is I'll do tree.insert(key, item) instead of tree.insert(key, value), where item is a struct { Key, Value }. That's fine, and I have other data structures in the benchmark that already need that; not everything stores the unprocessed key, and it sounds like that's the case here.

Yeah, I think that this is probably best for your scenario.  

That being said, I'll probably hold off on exposing the Key for each leaf node; it seems like it might confuse the consumer since the key is processed.

Thanks for the suggestion!

**Comment by tv42** [comment]
In that case, definitely do not expose it.

**Comment by tv42** [comment]
Oh, I failed to share the results here: https://github.com/tv42/benchmark-ordered-map
